# Generated by Django 3.1.3 on 2020-11-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(verbose_name='Order Date'),
        ),
    ]
